//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLog
    {
        public int id { get; set; }
        public Nullable<System.DateTime> day { get; set; }
        public Nullable<double> totalTime { get; set; }
        public Nullable<int> lampId { get; set; }
    }
}
